### ISSUE TITLE
i love this game

### ISSUE THREAD

**Issue by theplug22** [justinleonardo/Blocl#1]
![anthony-santos](https://cloud.githubusercontent.com/assets/14943588/11125280/f144f406-891d-11e5-9ec0-6af884a0d102.jpg)
![ty](https://cloud.githubusercontent.com/assets/14943588/11125281/f14626dc-891d-11e5-9995-70ed06d60f78.jpg)

my faves

**Comment by justinleonardo** [comment]
guck you

**Comment by theplug22** [comment]
justin sucks

**Comment by justinleonardo** [comment]
that hurts my feelings

**Comment by justinleonardo** [comment]
holy

**Comment by justinleonardo** [comment]
carp

**Comment by theplug22** [comment]
agreed

**Comment by theplug22** [comment]
nice work me

**Comment by justinleonardo** [comment]
i have taken your imput into consideration and after much thinking and consideration i have decided i will help you learn to spell words.

**Comment by justinleonardo** [comment]
http://www.google.com/imgres?imgurl=https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAMYAAAAJDgxMzE4NWUyLWY0YjMtNDU4NS05ZjA3LWJiYWE2MGM4MDk1Ng.jpg&imgrefurl=https://www.linkedin.com/pub/ken-masumoto/100/814/838&h=400&w=400&tbnid=0NDqOXMhNAN8yM:&docid=P2z6igpwb_ShYM&itg=1&ei=tMdEVveAMsSzogT6rpewAw&tbm=isch&ved=0CB0QMygAMABqFQoTCPeqm4Kwi8kCFcSZiAodetcFNg
