### ISSUE TITLE
ken is better then ken

### ISSUE THREAD

**Issue by theplug22** [justinleonardo/Blocl#3]
its fake

**Comment by justinleonardo** [comment]
andy sucks

**Comment by theplug22** [comment]
leave andy alone

**Comment by theplug22** [comment]
antony santos makes the best songs

**Comment by justinleonardo** [comment]
that is agreed

**Comment by justinleonardo** [comment]
santos is a star

**Comment by justinleonardo** [comment]
the plug is for the toilet

**Comment by theplug22** [comment]
![34dfe22](https://cloud.githubusercontent.com/assets/14943588/11306971/0dd0c972-8f6a-11e5-9387-3384ac4e48f8.jpg)

**Comment by KJMEUA** [comment]
is even what this? is even

**Comment by justinleonardo** [comment]
is odd

**Comment by justinleonardo** [comment]
tony santos is mi heroe

**Comment by justinleonardo** [comment]
bachatatatatachatatatata

**Comment by theplug22** [comment]
i luv anthony santos

**Comment by justinleonardo** [comment]
me amo antony santos

**Comment by KJMEUA** [comment]
<3

**Comment by KJMEUA** [comment]
> 3

**Comment by justinleonardo** [comment]
w>t

**Comment by theplug22** [comment]
> greentext

**Comment by KJMEUA** [comment]
> :#

**Comment by theplug22** [comment]
i hate ken

**Comment by justinleonardo** [comment]
camerontext

**Comment by KJMEUA** [comment]
Kappa

**Comment by justinleonardo** [comment]
#camhatesken

**Comment by KJMEUA** [comment]
Riperoni

**Comment by justinleonardo** [comment]
http://images1.freshpatents.com/img-featured/20150528/20150147600.png

**Comment by theplug22** [comment]
![2c69920b5b8369f689b18ce2e44e209b_400x400](https://cloud.githubusercontent.com/assets/14943588/11307091/c9369a3e-8f6a-11e5-975d-6d804a9aa54d.jpeg)

**Comment by justinleonardo** [comment]
kenjin masumoto from masumoto motors

**Comment by justinleonardo** [comment]
kenjin masumoto from masumoto motors

**Comment by theplug22** [comment]
Mr. Labi taught me so much french

**Comment by justinleonardo** [comment]
https://sturdyblog.files.wordpress.com/2012/07/gull_cameron.jpg
cameron

**Comment by KJMEUA** [comment]
what even is even odd

**Comment by theplug22** [comment]
![920x920](https://cloud.githubusercontent.com/assets/14943588/11307124/104d69de-8f6b-11e5-9847-180a0cd5a137.jpg)

**Comment by theplug22** [comment]
![officer_earl](https://cloud.githubusercontent.com/assets/14943588/11307145/2d6fefa0-8f6b-11e5-920b-e72c8b8d0426.png)

**Comment by justinleonardo** [comment]
there once was a group of people, named Somebody, Everybody, Anybody, and Nobody.  There was some spilled milk on the floor, and Anybody could've spilled it, but Everybody said Nobody did it.  "Well, Somebody must've spilled it," Everybody said.  But Nobody knew who spilled it.  It was Andy.

**Comment by ndmerrill** [comment]
wtf
