### ISSUE TITLE
important question

### ISSUE THREAD

**Issue by theplug22** [justinleonardo/Blocl#6]
where's anthony?

**Comment by justinleonardo** [comment]
?!?!?!?!?!?!?!?!
-Justin Juskyies

On Thu, Jan 14, 2016 at 8:30 AM, Cameron notifications@github.com wrote:

> where's anthony?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/justinleonardo/Blocl/issues/6.

## 
-  ~ JUSTIN*

**Comment by theplug22** [comment]
I'm stupid

**Comment by theplug22** [comment]
Leave a comment

**Comment by theplug22** [comment]
stop that justin

**Comment by theplug22** [comment]
where's anthony?????!?!?!

**Comment by KJMEUA** [comment]
??
???
????
?????

**Comment by justinleonardo** [comment]
FEDORRRRRRRRRRRR
